apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.fullname" . }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9200
  selector:
    {{- include "opensearch.selectorLabels" . | nindent 6 }}

